name: HealthTag
version: 3.1.0
author: Shelly7w7
main: shelly7w7\HealthTag\Main
description: "It will show the health of player above the head."
api: [5.0.0]
permissions:
  healthtag.configure:
    default: op

